//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IgooanaApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IgooanaApp.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Available.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must allow accessing your information in order to use the application.
        /// </summary>
        public static string OAuthUserConsentDenyMessage {
            get {
                return ResourceManager.GetString("OAuthUserConsentDenyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0:N0} other countries.
        /// </summary>
        public static string VisitsByCountryCountriesRestTemplatePlural {
            get {
                return ResourceManager.GetString("VisitsByCountryCountriesRestTemplatePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0:N0} other country.
        /// </summary>
        public static string VisitsByCountryCountriesRestTemplateSingle {
            get {
                return ResourceManager.GetString("VisitsByCountryCountriesRestTemplateSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from {0}.
        /// </summary>
        public static string VisitsByCountryStringTemplate {
            get {
                return ResourceManager.GetString("VisitsByCountryStringTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audience.
        /// </summary>
        public static string VisitsByCountryTitle {
            get {
                return ResourceManager.GetString("VisitsByCountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visits.
        /// </summary>
        public static string VisitsByCountryTotal {
            get {
                return ResourceManager.GetString("VisitsByCountryTotal", resourceCulture);
            }
        }
    }
}
